---
title: "Preprocessing"
output: html_document
date: "2023-05-03"
---

## Data Preprocessing

```{r libraries}
#Libraries
library(tidyverse)
library(readxl)
library(lubridate)
library(zoo)
library(xts)
library(dplyr)
library(data.table)
library(imputeTS)
library(ggplot2)
library(MTS)
library(tseries)
library(forecast)
library(bvartools)
library(coda)
library(spam)

data <- read_excel("data.xlsx", sheet = 'Data')
```


```{r from char to num, echo=FALSE}
data$Pigs_heads <- as.numeric(data$Pigs_heads)
data$Head_sheep <- as.numeric(data$Head_sheep)
data$Head_goat <- as.numeric(data$Head_goat)
data$Share_of_land_under_permanent_crops <- as.numeric(data$Share_of_land_under_permanent_crops)
data$Fertilizer_used_per_area_of_cropland <- as.numeric(data$Fertilizer_used_per_area_of_cropland)
data$Share_in_land_area_Forest_Land <- as.numeric(data$Share_in_land_area_Forest_Land)
```

```{r data imputation}
data$Rail_tracks_KM <- na_interpolation(data$Rail_tracks_KM, option = 'spline')
data$Total_freight_loaded_and_unloaded <- na_interpolation(data$Total_freight_loaded_and_unloaded, option = 'spline')
data$Chicken_heads <- na_interpolation(data$Chicken_heads, option = 'spline')
data$Turkeys_heads <- na_interpolation(data$Turkeys_heads, option = 'spline')
```

```{r merge common features}
data <- data %>% 
  mutate(livestock_heads = Pigs_heads + Head_sheep + Head_goat + 
           Chicken_heads + Turkeys_heads + Cattle_heads + Buffalo_head) 

data <- data %>% 
  mutate(res_capacity = hydro_capacity + geothermal_capacity + 
           wind_capacity + solar_capacity + biofuels_capacity + 
           biogas_capacity + waste_capacity)

data <- data %>% dplyr::select(Year, net_greenhouse_pc, environmental_taxes, `GDP pc`,
                                 industrial_production, energy_imp_dep, naturalgas_imports,
                                 oil_imports, total_energy_supply, gross_electricity_production,
                                 res_capacity, livestock_heads,
                                 Share_of_land_under_permanent_crops, Area_harvested_Rice,
                                 Fertilizer_used_per_area_of_cropland, Share_in_land_area_Forest_Land,
                                 Rail_tracks_KM, Length_of_motorways, Number_of_motorcycle, Total_freight_loaded_and_unloaded)
```


```{r scale data}
data <- apply(data, MARGIN = 2, FUN = scale)
data <- data.frame(data)
```

```{r first differences}
net_greenhouse_pc_1 <- diff(data$net_greenhouse_pc, differences = 1)
GDP_pc_1 <- diff(data$GDP.pc, differences = 1)
industrial_production_1 <- diff(data$industrial_production, differences = 1)
energy_imp_dep_1 <- diff(data$energy_imp_dep, differences = 1)
naturalgas_imports_1  <- diff(data$naturalgas_imports , differences = 1)
oil_imports_1  <- diff(data$oil_imports , differences = 1)
total_energy_supply_1 <- diff(data$total_energy_supply , differences = 1)
gross_electricity_prod_1 <- diff(data$gross_electricity_production, differences = 1)
Share_of_land_under_permanent_crops_1 <- diff(data$Share_of_land_under_permanent_crops , differences = 1)
Area_harvested_Rice_1 <- diff(data$Area_harvested_Rice, differences = 1)
```


